/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  safelist: [
    'text-white',
    'bg-green-500',
    'dark:bg-green-700',
    'dark:text-green-200',
    'text-red-500',
    'bg-red-100',
    'dark:bg-red-800',
    'dark:text-red-200',
    'text-yellow-500',
    'bg-yellow-100',
    'dark:bg-yellow-800',
    'dark:text-yellow-200',
    'text-blue-500',
    'bg-blue-100',
    'dark:bg-blue-800',
    'dark:text-blue-200',
    'text-gray-700',
    'bg-green-100',
    'dark:bg-green-800',
    'bg-red-100',
    'dark:bg-red-800',
    'bg-yellow-100',
    'dark:bg-yellow-800',
    'bg-blue-100',
    'dark:bg-blue-800',
    'bg-green-500',
    'text-white',
    'hover:bg-green-600',
    'focus:ring-green-400',
    'dark:bg-green-700',
    'dark:hover:bg-green-600',
    'bg-red-100',
    'text-red-500',
    'hover:bg-red-200',
    'focus:ring-red-400',
    'dark:bg-red-800',
    'dark:text-red-200',
    'dark:hover:bg-red-700',
    'bg-yellow-100',
    'text-yellow-500',
    'hover:bg-yellow-200',
    'focus:ring-yellow-400',
    'dark:bg-yellow-800',
    'dark:text-yellow-200',
    'dark:hover:bg-yellow-700',
    'bg-blue-100',
    'text-blue-500',
    'hover:bg-blue-200',
    'focus:ring-blue-400',
    'dark:bg-blue-800',
    'dark:text-blue-200',
    'dark:hover:bg-blue-700',
  ],
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    "./resources/views/vendor/pagination/**/*.blade.php",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', "Segoe UI", 'Roboto', "Helvetica Neue", 'Arial', "Noto Sans", 'sans-serif', "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"],
        serif: ['Cormorant', 'Georgia', 'serif'],
      },
      colors: {
        'primary-red': '#E00000',
        'dark-text': '#333333',
        'light-text': '#666666',
        'page-background': '#F5F5F5',
        'card-background': '#FFFFFF',
        'border-light': '#E0E0E0',
        // Keeping existing Prothom Alo specific colors if they are used elsewhere
        'prothomalored': '#e00000',
        'prothomalo-blue': '#007bff',
        'prothomalo-gray': '#f1f1f1',
        'prothomalo-dark-gray': '#333333',
        'sidebar-blue': '#2F8EBA',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
      },
      boxShadow: {
        DEFAULT: '0 1px 2px rgba(0, 0, 0, 0.05)',
      },
      animation: {
        ticker: 'ticker 40s linear infinite',
      },
      keyframes: {
        ticker: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        }
      }
    },
  },
  plugins: [],
}