/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  safelist: [
    'text-white',
    'bg-green-500',
    'dark:bg-green-700',
    'dark:text-green-200',
    'text-red-500',
    'bg-red-100',
    'dark:bg-red-800',
    'dark:text-red-200',
    'text-yellow-500',
    'bg-yellow-100',
    'dark:bg-yellow-800',
    'dark:text-yellow-200',
    'text-blue-500',
    'bg-blue-100',
    'dark:bg-blue-800',
    'dark:text-blue-200',
    'text-gray-700',
    'bg-green-100',
    'dark:bg-green-800',
    'bg-red-100',
    'dark:bg-red-800',
    'bg-yellow-100',
    'dark:bg-yellow-800',
    'bg-blue-100',
    'dark:bg-blue-800',
    'bg-green-500',
    'text-white',
    'hover:bg-green-600',
    'focus:ring-green-400',
    'dark:bg-green-700',
    'dark:hover:bg-green-600',
    'bg-red-100',
    'text-red-500',
    'hover:bg-red-200',
    'focus:ring-red-400',
    'dark:bg-red-800',
    'dark:text-red-200',
    'dark:hover:bg-red-700',
    'bg-yellow-100',
    'text-yellow-500',
    'hover:bg-yellow-200',
    'focus:ring-yellow-400',
    'dark:bg-yellow-800',
    'dark:text-yellow-200',
    'dark:hover:bg-yellow-700',
    'bg-blue-100',
    'text-blue-500',
    'hover:bg-blue-200',
    'focus:ring-blue-400',
    'dark:bg-blue-800',
    'dark:text-blue-200',
    'dark:hover:bg-blue-700',
  ],
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    "./resources/views/vendor/pagination/**/*.blade.php",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      colors: {
        bg: '#ffffff',
        surface: '#f8fafc',
        'surface-2': '#f1f5f9',
        card: '#ffffff',
        text: '#0f172a',
        muted: '#64748b',
        'light-text': '#94a3b8',
        accent: '#38bdf8',
        primary: {
          DEFAULT: '#0ea5e9',
          '700': '#0284c7',
          '900': '#075985',
        },
        danger: '#ef4444',
        border: 'rgba(14, 165, 233, 0.2)',
      },
      borderRadius: {
        DEFAULT: '12px',
      },
      boxShadow: {
        DEFAULT: '0 10px 30px rgba(2, 6, 23, 0.35)',
      },
      animation: {
        ticker: 'ticker 40s linear infinite',
      },
      keyframes: {
        ticker: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        }
      }
    },
  },
  plugins: [],
}